### ISSUE TITLE
✨ Customer List | Add customer search

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/Scruminati.AdminUI#1]
### Description
As an admin, I want to be able to search for customers using their customer name, so I can easily find who I'm looking for.

### Tasks
- [ ] Add searchbox to customer list
- [ ] Filter customers based off search text

### Acceptance Criteria
- [ ] Searchbox works
- [ ] When no records are found, a message saying "No customers matching {{ searchtext }}" is shown.
