### ISSUE TITLE
📝 Instructions | Write customer complaints script

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/Scruminati.AdminUI#2]
### Description
Some customers complain. Let's create a way to politely tell them to bugger off.

### Tasks
- [ ] Write the script

### Acceptance Criteria
- [ ] Script is approved by legal team
- [ ] Script is uploaded to doc library
- [ ] Script shows on "common resources" list
